server {
    listen 80;

    client_max_body_size 50M;

    server_name my_server;

    index index.html; 

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://app:3000/;  
    }
}